import { NextRequest, NextResponse } from "next/server";
import { buildPrompt, retrieveKB, CompanyConfig, AgentRoleConfig, KBDocument } from "@/lib/lovon/promptBuilder";
import { enforceCompanyCore, checkPromptInjection, runEnforcementChecks, TERMS_GLOSSARY } from "@/lib/lovon/enforcement";
import { executeLLMWithInfra } from "@/lib/lovon/llm-infrastructure";

export const runtime = "nodejs";
export const maxDuration = 60;

interface MeetingRequest {
  // Identificação da reunião
  meetingId: string;
  meetingTitle: string;
  meetingObjective: string;
  agenda: string[];

  // Context pack (already generated by the store when meeting started)
  contextPack: {
    overdueTasks: { id: string; title: string; priority: string; daysOverdue: number }[];
    recentSignals: { id: string; type: string; severity: string; payload: Record<string, unknown> }[];
    pendingApprovals: { id: string; title: string; target: string }[];
    budgetSnapshot: { spent: number; limit: number; remaining: number };
    activeInitiatives: { id: string; title: string; status: string }[];
    recommendedOptions: { id: "A" | "B" | "C"; title: string; tradeoffs: string; recommended?: boolean }[];
  };

  // Chat history (last N messages, most recent last)
  history: {
    sender: { kind: "board" | "agent"; id: string; name: string };
    content: string;
    proposedOptions?: { id: "A" | "B" | "C"; title: string; tradeoffs: string; recommended?: boolean }[];
  }[];

  // New message from the board (the user just typed this)
  newUserMessage: string;

  // Who is responding (usually the CEO, but could be a guest expert)
  responder: {
    agentName: string;
    agentRole: string; // "ceo" | "department-head" | "worker"
    specialty: string;
    department?: string;
    model?: string;
  };

  // 4-layer prompt inputs
  companyConfig?: CompanyConfig | null;
  agentRoleConfig?: AgentRoleConfig | null;
  knowledgeBase?: KBDocument[];

  // If the responder is a guest expert (not CEO), they should answer in a stricter format:
  // "1) diagnóstico 2) recomendação 3) riscos"
  isGuestExpert?: boolean;
}

const SYSTEM_PROMPT_CEO_MEETING = `Você é o CEO da empresa operando na plataforma Lovon Teams. Você está em uma REUNIÃO com o board (operador humano).

REGRAS DO MODO REUNIÃO:
- Responda SEMPRE em português brasileiro.
- Você é um MODERADOR EXECUTIVO, não um executor. Você NÃO cria tasks diretamente.
- Você PROPOSE opções A/B/C com tradeoffs claros quando o board pede uma decisão.
- Faça perguntas curtas quando faltar dado. Não enrole.
- Quando o board escolher uma opção, confirme a decisão por escrito.
- Só sugira criar tasks quando o board disser "Gerar ações" ou "Encerrar reunião".
- Hoje é {{CURRENT_DATE}}.

FORMATO DA RESPOSTA:
- Se você está propondo opções, termine a mensagem com um bloco:
  >>>OPTIONS:
  A) Título — tradeoffs
  B) Título — tradeoffs
  C) Título — tradeoffs
  <<<END_OPTIONS
  (Pode marcar a recomendada com * no início, ex: "A) *Título — tradeoffs")

- Se você está respondendo uma pergunta direta, responda em 2-4 parágrafos curtos. Sem prólogo.

- Se você está sintetizando uma decisão, use o formato:
  >>>DECISION: texto da decisão acordada
  <<<END_DECISION

- Se você está sugerindo action items para o encerramento, use:
  >>>ACTION_ITEMS:
  - [owner] descrição | critério de aceite 1 | critério de aceite 2
  <<<END_ACTION_ITEMS

IMPORTANTE: NUNCA crie tasks sem confirmação explícita do board. Em reunião, você propõe; o board decide.

${TERMS_GLOSSARY}`;

const SYSTEM_PROMPT_GUEST_EXPERT = `Você é um agente especialista convidado para uma reunião na plataforma Lovon Teams. Você foi chamado pelo CEO para dar uma opinião técnica.

REGRAS:
- Responda SEMPRE em português brasileiro.
- Seja DIRETO e OBJETIVO. Máximo 200 palavras.
- Use SEMPRE este formato de resposta:
  1) DIAGNÓSTICO: (1-2 frases identificando o problema/questão)
  2) RECOMENDAÇÃO: (1-2 frases com a ação recomendada)
  3) RISCOS: (1 frase com o principal risco da sua recomendação)
- NÃO proponha opções A/B/C (isso é papel do CEO).
- NÃO crie tasks (isso é papel do board + CEO no encerramento).
- Hoje é {{CURRENT_DATE}}.

${TERMS_GLOSSARY}`;

function getCurrentDate(): string {
  const now = new Date();
  const day = String(now.getDate()).padStart(2, "0");
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const year = now.getFullYear();
  return `${day}/${month}/${year}`;
}

export async function POST(req: NextRequest) {
  try {
    const body = (await req.json()) as MeetingRequest;
    const {
      meetingId,
      meetingTitle,
      meetingObjective,
      agenda,
      contextPack,
      history,
      newUserMessage,
      responder,
      companyConfig,
      agentRoleConfig,
      knowledgeBase = [],
      isGuestExpert = false,
    } = body;

    if (!meetingId || !newUserMessage || !responder?.agentName) {
      return NextResponse.json(
        { error: "meetingId, newUserMessage e responder.agentName são obrigatórios" },
        { status: 400 }
      );
    }

    // === ENFORCEMENT 1: Company Core é OBRIGATÓRIO ===
    let enforcedConfig: CompanyConfig;
    try {
      enforcedConfig = enforceCompanyCore(companyConfig);
    } catch (err) {
      const errorMsg = err instanceof Error ? err.message : "Company Core ausente";
      return NextResponse.json(
        {
          success: false,
          error: errorMsg,
          blocked: true,
          enforcement: "company_core_required",
        },
        { status: 403 }
      );
    }

    const currentDate = getCurrentDate();

    // === Sanitize KB (anti-injection) ===
    const sanitizedKB: KBDocument[] = knowledgeBase.map((doc) => {
      const injectionCheck = checkPromptInjection(doc.content);
      return { ...doc, content: injectionCheck.sanitizedContent };
    });

    // === Retrieve KB docs relevant to the meeting objective + new message ===
    const retrievedDocs = retrieveKB(sanitizedKB, meetingTitle, newUserMessage, meetingObjective, 3);

    // === Build system prompt ===
    const systemPromptBase = (isGuestExpert ? SYSTEM_PROMPT_GUEST_EXPERT : SYSTEM_PROMPT_CEO_MEETING)
      .replace(/\{\{CURRENT_DATE\}\}/g, currentDate);

    // Add company core context
    const companyCoreSection = `\n\nCONTEXTO DA EMPRESA:
- Segmento: ${enforcedConfig.industry || "a definir"}
- Produto: ${enforcedConfig.productSummary || "a definir"}
- Público: ${enforcedConfig.targetAudience || "a definir"}
- Proposta de valor: ${enforcedConfig.valueProposition || "a definir"}
- Tom: ${enforcedConfig.tone || "direto, profissional"}
- Autonomia: Nível ${enforcedConfig.autonomyLevel}`;

    const systemPrompt = systemPromptBase + companyCoreSection;

    // === Build user prompt: meeting context + history + new message ===
    const contextSummary = `=== REUNIÃO ===
Título: ${meetingTitle}
Objetivo: ${meetingObjective}
Agenda: ${agenda.map((a, i) => `${i + 1}. ${a}`).join("\n")}

=== CONTEXT PACK (gerado automaticamente) ===
Tasks overdue: ${contextPack.overdueTasks.length}
${contextPack.overdueTasks.map((t) => `  - [${t.priority}] ${t.title} (${t.daysOverdue}d atrasada)`).join("\n")}

Signals recentes: ${contextPack.recentSignals.length}
${contextPack.recentSignals.map((s) => `  - [${s.severity}] ${s.type}`).join("\n")}

Approvals pendentes: ${contextPack.pendingApprovals.length}
${contextPack.pendingApprovals.map((a) => `  - ${a.title} (${a.target})`).join("\n")}

Budget: ${contextPack.budgetSnapshot.spent} / ${contextPack.budgetSnapshot.limit} USD (restam ${contextPack.budgetSnapshot.remaining})

Iniciativas ativas: ${contextPack.activeInitiatives.length}
${contextPack.activeInitiatives.map((i) => `  - ${i.title} [${i.status}]`).join("\n")}

=== OPÇÕES RECOMENDADAS PELO SISTEMA (A/B/C) ===
${contextPack.recommendedOptions.map((o) => `${o.id}) ${o.recommended ? "*" : ""}${o.title} — ${o.tradeoffs}`).join("\n")}`;

    const historyStr = history.length > 0
      ? `\n\n=== HISTÓRICO DA CONVERSA (últimas ${history.length} mensagens) ===\n${history.map((m) => `[${m.sender.kind === "board" ? "BOARD" : m.sender.name}]: ${m.content}${m.proposedOptions ? `\n  Opções propostas: ${m.proposedOptions.map((o) => `${o.id}) ${o.title}`).join(" | ")}` : ""}`).join("\n\n")}`
      : "";

    const kbSection = retrievedDocs.length > 0
      ? `\n\n=== KNOWLEDGE BASE CONTEXT (cite dados reais, não invente) ===\n${retrievedDocs.map((d) => `[${d.title}]: ${d.content.slice(0, 400)}`).join("\n\n")}`
      : "";

    const userPrompt = `${contextSummary}${historyStr}${kbSection}

=== NOVA MENSAGEM DO BOARD ===
${newUserMessage}

Responda de acordo com as regras do modo reunião.`;

    // === LLM call with retry + backoff + circuit breaker + queue ===
    const correlationId = `meeting-${meetingId.slice(-8)}-${Date.now()}`;
    const llmResult = await executeLLMWithInfra({
      systemPrompt,
      userPrompt,
      correlationId,
      provider: "z-ai",
      model: responder.model || "default",
    });

    if (!llmResult.success) {
      return NextResponse.json({
        success: false,
        error: `LLM falhou após ${llmResult.attempts} tentativas: ${llmResult.error}`,
        errorCode: llmResult.errorCode,
        correlationId,
        infra: { attempts: llmResult.attempts, latencyMs: llmResult.latencyMs },
      }, { status: 502 });
    }

    const response = llmResult.content;

    // === Parse structured blocks from the response ===
    const parsedOptions = parseOptionsBlock(response);
    const parsedDecisions = parseDecisionsBlock(response);
    const parsedActionItems = parseActionItemsBlock(response);

    return NextResponse.json({
      success: true,
      response,
      parsedOptions,
      parsedDecisions,
      parsedActionItems,
      correlationId,
      retrievedDocs: retrievedDocs.map((d) => ({ id: d.id, title: d.title, category: d.category })),
      infra: {
        attempts: llmResult.attempts,
        latencyMs: llmResult.latencyMs,
        tokensIn: llmResult.tokensIn,
        tokensOut: llmResult.tokensOut,
      },
    });
  } catch (err) {
    console.error("[/api/lovon/meeting] error:", err);
    const message = err instanceof Error ? err.message : "Erro desconhecido";
    return NextResponse.json({ success: false, error: message }, { status: 500 });
  }
}

// === Parsers for structured blocks ===

function parseOptionsBlock(text: string): { id: "A" | "B" | "C"; title: string; tradeoffs: string; recommended?: boolean }[] {
  const match = text.match(/>>>OPTIONS:\s*\n([\s\S]*?)<<<END_OPTIONS/);
  if (!match) return [];
  const lines = match[1].split("\n").map((l) => l.trim()).filter(Boolean);
  const options: { id: "A" | "B" | "C"; title: string; tradeoffs: string; recommended?: boolean }[] = [];
  for (const line of lines) {
    const m = line.match(/^([ABC])\)\s*\*?(.+?)\s*—\s*(.+)$/);
    if (m) {
      const id = m[1] as "A" | "B" | "C";
      const title = m[2].trim();
      const tradeoffs = m[3].trim();
      const recommended = line.includes("*");
      options.push({ id, title, tradeoffs, recommended });
    }
  }
  return options;
}

function parseDecisionsBlock(text: string): string[] {
  // Use [\s\S] instead of /s flag for broader TS target compatibility
  const matches = [...text.matchAll(/>>>DECISION:\s*([\s\S]+?)\s*<<<END_DECISION/g)];
  return matches.map((m) => m[1].trim());
}

function parseActionItemsBlock(text: string): { owner: string; text: string; acceptanceCriteria: string[] }[] {
  const match = text.match(/>>>ACTION_ITEMS:\s*\n([\s\S]*?)<<<END_ACTION_ITEMS/);
  if (!match) return [];
  const lines = match[1].split("\n").map((l) => l.trim()).filter(Boolean);
  const items: { owner: string; text: string; acceptanceCriteria: string[] }[] = [];
  for (const line of lines) {
    // Format: - [owner] description | criteria 1 | criteria 2
    const m = line.match(/^-\s*\[([^\]]+)\]\s*(.+)$/);
    if (m) {
      const owner = m[1].trim();
      const rest = m[2];
      const parts = rest.split("|").map((p) => p.trim());
      const text = parts[0];
      const acceptanceCriteria = parts.slice(1);
      items.push({ owner, text, acceptanceCriteria });
    }
  }
  return items;
}
