services:
  - type: web
    name: lovon-teams-v1
    runtime: node
    plan: free
    region: oregon
    buildCommand: "npm install --legacy-peer-deps --include=dev && npx prisma generate && npx prisma db push --skip-generate && npm run build"
    startCommand: "NODE_ENV=production HOSTNAME=0.0.0.0 node .next/standalone/server.js"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: file:./db/custom.db
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: onboarding@resend.dev
      - key: RESEND_FROM_NAME
        value: Lovon Teams
      - key: HOSTNAME
        value: 0.0.0.0
      - key: PORT
        sync: false
